# config/knowledge_graph/wn18rr_visualize.yaml

output_dir: ~/experiments/wn18rr_visualize/

dataset:
  class: WN18RR
  path: /home/ma/ma_ma/ma_leonenge/datasets/knowledge_graphs

task:
  class: KnowledgeGraphCompletion
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    remove_one_hop: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  full_batch_eval: yes

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 64

checkpoint: ~/experiments/wn18rr/model_epoch_20.pth

metric: mrr
